name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # 접속 별명 설정
          cat >>~/.ssh/config <<END
          Host umc9thworkbook
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
            BatchMode yes
            ConnectTimeout 10
          END
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Workspace
        run: |
          echo "Testing SSH connection..."
          ssh umc9thworkbook 'echo "SSH Connection successful"'
          
          echo "Creating directory..."
          ssh umc9thworkbook 'sudo mkdir -p /opt/app'
          
          echo "Changing ownership..."
          ssh umc9thworkbook 'sudo chown ubuntu:ubuntu /opt/app'
          
          echo "Copying files..."
          scp -r ./[!.]* umc9thworkbook:/opt/app

      - name: Install dependencies
        run: |
          ssh umc9thworkbook 'npm install --prefix /opt/app/'

      - name: Copy systemd service file
        run: |
          ssh umc9thworkbook '
            echo "[Unit]
            Description=UMC 9th Project
            After=network.target

            [Service]
            User=ubuntu
            ExecStart=/usr/bin/npm run dev --prefix /opt/app/
            Restart=always

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
          '

      - name: Enable systemd service
        run: |
          ssh umc9thworkbook 'sudo systemctl daemon-reload'
          ssh umc9thworkbook 'sudo systemctl enable app'

      - name: Restart systemd service
        run: |
          ssh umc9thworkbook 'sudo systemctl restart app'